name: 'Install deployqt'
description: 'Install LinuxdeployQt/ on your Github Actions workflows with just one simple action'
author: 'miurahr'
branding:
  icon: 'package'
  color: 'green'
inputs:
  dir:
    description: 'Directory to install'
runs:
  using: 'node12'
  main: 'lib/main.js'
