name: Test Installing LinuxDeployQt

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: "npm install"
        run: npm install
      - name: "npm run build"
        run: npm run build
      - name: Install LinuxDeployQt
        uses: ./
      - name: Install dependency
        run: |
          sudo apt install -y libxkbcommon-x11-0
        shell: bash
      - name: Configure and build test project
        run: |
          tar xJf QtWidgetsApplication.tar.xz
          cd QtWidgetsApplication/
          qmake QtWidgetsApplication.pro
          make -j2
          mkdir -p appdir/usr/bin
          make INSTALL_ROOT=appdir -j2 install ; find appdir/
        shell: bash
      - name: Run LinuxDeployQt
        run: |
          cd QtWidgetsApplication/
          linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/QtWidgetsApplication.desktop -appimage
          echo "SUCCESS"
        shell: bash
